### ISSUE TITLE
Main loop: navigator.mozTCPSocket not available

### ISSUE THREAD

**Issue by mrmrmrmr1** [feklee/ptp.js#3]
Hi,

When I try this on my Chrome browser with PTP server IP 192.168.1.1, I get the error:
Main loop: navigator.mozTCPSocket not available

I've checked the code and couldn't identify where the problem is. What may be missing on my configuration ?

**Comment by feklee** [comment]
Thanks for the report! Please note that Chrome does not support the [TCP Socket API][1], which is required to communicate via PTP/IP from a browser. As far as I know, this API has never been implemented outside of Firefox and in particular FirefoxOS (B2G). You can however use *ptp.js* with Node.

[1]: https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/API/TPC_Socket_API
